"""Initial migration

Revision ID: 71059f9b41b6
Revises: 
Create Date: 2024-08-02 03:30:45.530772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71059f9b41b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_invitation_link', ['invitation_link'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.create_foreign_key('fk_user_inviter_id', 'user', ['inviter_id'], ['id'])
        batch_op.create_foreign_key('fk_user_sponsor_id', 'user', ['sponsor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_inviter_id', type_='foreignkey')
        batch_op.drop_constraint('fk_user_sponsor_id', type_='foreignkey')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_invitation_link', type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###